(define-module (roquix packages planify)
  #:use-module (guix packages)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix build-system meson)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages calendar)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages icu4c)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages sqlite)
  #:use-module (gnu packages xml))

(define-public gxml
  (package
    (name "gxml")
    (version "0.20.4")
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://codeload.github.com/GNOME/gxml/tar.gz/"
                           "refs/tags/" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "19a1swllis0485dvp5zh40bh8hxdvzdbfc50pxw77amnhhwmszr3"))))
    (build-system meson-build-system)
    (arguments
     (list
      #:configure-flags #~(list "-Ddocs=false")
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'fix-type-cache
            (lambda _
              ;; GType keys are pointer-sized values, not pointers to ints.
              ;; Comparing their pointees aliases distinct collection types.
              ;; https://docs.gtk.org/glib/func.direct_equal.html
              (substitute* '("gxml/XParser.vala" "gxml/XdParser.vala")
                (("int_hash, int_equal") "direct_hash, direct_equal"))))
          (add-after 'unpack 'fix-pkg-config-requirements
            (lambda _
              ;; pkg-config requires separate operator and version tokens.
              (substitute* "gxml/gxml.pc.in"
                ((">=([0-9])" _ digit) (string-append ">= " digit)))))
          (add-after 'install 'check-pkg-config
            (lambda* (#:key outputs (tests? #t) #:allow-other-keys)
              (when tests?
                (setenv "PKG_CONFIG_PATH"
                        (string-append (assoc-ref outputs "out")
                                       "/lib/pkgconfig:"
                                       (getenv "PKG_CONFIG_PATH")))
                (invoke "pkg-config" "--cflags" "--libs" "gxml-0.20")))))))
    (native-inputs
     (list gettext-minimal gobject-introspection pkg-config vala))
    (propagated-inputs
     (list glib libgee libxml2))
    (home-page "https://gitlab.gnome.org/GNOME/gxml")
    (synopsis "GObject API for XML documents")
    (description
     "GXml provides a GObject API for XML documents, DOM interfaces, XPath
queries, and serialization of GObject properties to XML.")
    (license license:lgpl2.1+)))

(define-public vala-chrono
  (package
    (name "vala-chrono")
    (version "1.0.0")
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://codeload.github.com/alainm23/chrono/tar.gz/"
                           "refs/tags/" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "1w03qgfn057z152m01bpzr9ym11abim3jiqa88mws0mkcyhkaakx"))))
    (build-system meson-build-system)
    (arguments
     (list #:configure-flags #~(list "-Ddocs=false" "-Dtests=true")))
    (native-inputs (list pkg-config vala))
    (propagated-inputs (list glib libgee))
    (home-page "https://github.com/alainm23/chrono")
    (synopsis "Natural language date parser for Vala and GLib")
    (description
     "Chrono parses natural language dates, times, and recurrence rules in
English and Spanish.  It provides a shared library and Vala bindings for GLib
applications.")
    (license license:gpl3+)))

(define-public planify
  (package
    (name "planify")
    (version "4.20.0")
    (source
     (origin
       (method url-fetch)
       (uri (string-append "https://codeload.github.com/alainm23/planify/tar.gz/"
                           "refs/tags/v" version))
       (file-name (string-append name "-" version ".tar.gz"))
       (sha256
        (base32 "0rbv8i73n0niqwwmyidqqkyf2l3m66dl3dcvdhkq0rp3cvn2hsd4"))))
    (build-system meson-build-system)
    (arguments
     (list
      #:glib-or-gtk? #t
      #:configure-flags
      #~(list "-Dprofile=default"
              "-Dspelling=enabled"
              "-Dportal=true"
              "-Devolution=true"
              "-Dgoa=true"
              "-Dmanpage=true")
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'disable-icon-cache-update
            (lambda _
              ;; Guix profiles combine icons from multiple immutable outputs.
              ;; Their cache is generated by the profile hook.
              (substitute* "meson.build"
                (("gtk_update_icon_cache: true")
                 "gtk_update_icon_cache: false"))))
          (add-before 'check 'prepare-test-settings
            (lambda _
              ;; Core tests instantiate GSettings before the install phase.
              (mkdir-p "test-schemas")
              (for-each (lambda (schema) (install-file schema "test-schemas"))
                        (find-files
                         #$(string-append "../planify-" version "/data")
                         "\\.gschema\\.xml$"))
              (invoke "glib-compile-schemas" "test-schemas")
              (setenv "GSETTINGS_SCHEMA_DIR"
                      (string-append (getcwd) "/test-schemas"))
              (setenv "GSETTINGS_BACKEND" "memory")))
          (add-after 'glib-or-gtk-compile-schemas 'check-installed-cli
            (lambda* (#:key inputs outputs (tests? #t) #:allow-other-keys)
              (when tests?
                (let* ((out (assoc-ref outputs "out"))
                       (home (mkdtemp
                              (string-append (getcwd) "/planify-cli-XXXXXX")))
                       (data (string-append home "/data"))
                       (backup (string-append home "/backup.json")))
                  (dynamic-wind
                    (lambda ()
                      ;; The GUI normally creates the CLI's data directory.
                      (mkdir-p
                       (string-append data "/io.github.alainm23.planify")))
                    (lambda ()
                      ;; Build-time schemas must not hide a broken wrapper.
                      ;; Critical errors can otherwise leave the CLI exiting 0.
                      ;; https://docs.gtk.org/glib/running.html
                      (invoke (which "env") "-i"
                              (string-append "HOME=" home)
                              (string-append "PATH=" out "/bin")
                              (string-append "XDG_DATA_HOME=" data)
                              (string-append "XDG_DATA_DIRS=" home "/empty")
                              (string-append "XDG_CONFIG_HOME=" home "/config")
                              (string-append "XDG_CACHE_HOME=" home "/cache")
                              "GSETTINGS_BACKEND=memory"
                              "G_DEBUG=fatal-criticals"
                              "LC_ALL=C.UTF-8"
                              (string-append
                               out "/bin/io.github.alainm23.planify.cli")
                              "backup" "--output" backup)
                      (invoke (search-input-file
                               inputs "/bin/json-glib-validate")
                              "--strict" backup))
                    (lambda () (delete-file-recursively home))))))))))
    (native-inputs
     (list (list "desktop-file-utils" desktop-file-utils)
           (list "gettext-minimal" gettext-minimal)
           (list "glib:bin" glib "bin")
           (list "pkg-config" pkg-config)
           (list "vala" vala)))
    (inputs
     (list bash-minimal evolution-data-server glib glib-networking
           gnome-online-accounts gtk gtksourceview gxml icu4c json-glib
           libadwaita libgee libical libportal libsecret libsoup libspelling
           pango sqlite vala-chrono))
    (home-page "https://github.com/alainm23/planify")
    (synopsis "Task manager for GNOME with Todoist and CalDAV support")
    (description
     "Planify organizes tasks and projects with reminders, recurring tasks,
labels, and a calendar view.  It supports local task lists, Todoist, CalDAV,
Nextcloud, and Nextcloud Deck, and includes a command-line interface, a quick-add
window, and a GNOME Shell search provider.")
    (license license:gpl3+)))
