name: "Build updated packages"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (cons
             (channel
              (name 'roquix)
              (url "https://github.com/ROCKTAKEY/roquix")
              (commit "${{ github.sha }}"))
             %default-channels)
      - run: guix --version
      - run: guix describe
      - name: List packages to build
        id: packages-to-build
        run: bash scripts/list-package.sh ${{ github.repository }} ${{ github.event.before }} ${{ github.event.after }}
      - name: Build each package
        run: bash scripts/build-package.sh ${{ steps.packages-to-build.outputs.PACKAGES_TO_BUILD }}
