name: "Build all packages"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (cons
             (channel
              (name 'roquix)
              (url "https://github.com/ROCKTAKEY/roquix")
              (commit "${{ github.sha }}"))
             %default-channels)
      - run: guix --version
      - run: guix describe
      - name: Build each package
        run: |
          for i in `guix package -A | awk '$4 ~ "^roquix/" { print $1 }'`;
            do
            echo "::group::Build $i:";
            guix build $i
            echo "::endgroup::"
          done
