name: "Build all packages"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: |
            guix-cache-
      - uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |-
            (cons
             (channel
              (name 'roquix)
              (url "file://${GITHUB_WORKSPACE}"))
             %default-channels)
      - run: guix --version
      - name: Build each package
        run: |
          for i in `guix package -A | awk '$4 ~ "^roquix/" { print $1 }'`;
            do echo "Build $i:";
            guix build $i
          done
