name: test

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: PromyLOPh/guix-install-action@v1
      - run: guix pull
